baseurl = "https://www.jonasgathen.com/"
languageCode = "en-US"
title = "Jonas Gathen"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

# Recommended option
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "portrait.jpg"
  author = "Jonas Gathen"
  description = "This is my academic website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "jgathen"
  Email         = "j.gathen@posteo.de"
  LinkedIn      = "jonas-gathen-07a5b866"

## Main Menu
[[menu.main]]
  name = "research statement"
  identifier = "research_statement"
  weight = 100
  url = "/research_statement/"
[[menu.main]]
  name = "research"
  identifier = "research"
  weight = 200
  url = "/research/"
[[menu.main]]
  name = "blog"
  weight = 300
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "CV"
  identifier = "CV"
  weight = 400
  url = "/CV.pdf"
[[menu.main]]
  name = "reading list"
  identifier = "reading list"
  weight = 500
  url = "/reading_list/"
  
