---
title: "Research statement"
author: "Jonas Gathen"
date: "2022-12-10T00:00:00"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I am fundamentally interested in how societies change in the process of development and the underlying causes of such economy-wide changes. This is for me the substantive definition of the field of Macro Development. Methodologically, this means combining rich micro data that allows to disentangle fundamental mechanisms of economy-wide changes with theoretical/structural models that allow to sharpen the focus on processes and changes that truly matter at the aggregate level. 

My research interests within Macro Development are broad: I am interested in growth, structural change and industrial development, long-run changes in income and wealth inequality, firm dynamics, entrepreneurship and occupational choices, the role of the government and elites as well as how many of these factors interact over the course of development. Throughout, my research focus is on long-run changes (processes that play out over decades) rather than short- to medium-run changes. Most of my work is on better understanding long-run development processes instead of direct policy questions, but all of my papers have important policy implications. 

My current work can be structured into two primary areas of interest: first, better understanding the dynamics of development and the drivers of long-run growth and structural change. And second, the political economy of development; specifically, how the state and private sector interact over the course of development. I discuss each in turn and then end with a few thoughts on future topics I plan to work on and open questions in Macro Development that I find important. 

## The dynamics of development and the drivers of long-run growth and structural change

Economic development is characterized by large changes in the economy. In my Job Market Paper (JMP) with Oscar Fentanes, we look at 40 years of Indonesian development (1975-2015). Over this time, aggregate output grew by a factor of 15, the working population grew three-fold and the economy saw dramatic changes in the reallocation of resources across sectors (e.g. the manufacturing employment and output share increased 2.5-fold) and - as we document - across firms. Despite the evident importance of these changes, research in Macro Development - mostly due to methodological reasons - has struggled to link these aggregate dynamics of development to changes in household and firm behavior at the micro level. In my JMP, we tackle this issue using 40 years of micro data on manufacturing plants and a structural model that allows to link plant-level dynamics to aggregate changes in the economy. 

In the paper, we are interested in the drivers of economic growth. Economic growth, by an accounting definition, simply captures changes in the reallocation of resources and technology across sectors and firms. Of the growth that we observe, some is likely driven by changes in policy, changes in frictions and technological change across firms and sectors. In the paper, we propose a new framework that allows to revisit a key question in Macro Development that has so far been difficult to answer: How much growth that we observe in the data is simply pre-determined by **initial conditions**? By initial conditions, we specifically mean two components that are key in theories of economic growth: (1) *initial conditions in the level* of factor inputs and technology across the economy. For example, the neoclassical growth model predicts fast catch-up growth in case the initial economy is below its steady state capital-output ratio (King & Rebelo '93) as the economy goes through a period of rapid factor accumulation and deepening. This catch-up growth dynamic has been found to explain Japanese and German post-WW2 growth, growth of post-USSR economies as well as the Asian Tiger economies and China (e.g. Chen et al '06, Alvarez-Cuadrado & Pintea '09). And (2) *initial conditions in the distribution* of factor inputs and technology across the economy. As has been emphasized in the misallocation literature, growth can come from simply reallocating resources from less productive to more productive sectors and firms while holding the level of technology and resources fixed. Growth can then be driven by an undoing of misallocation over time - a driver of growth that has been found to have the potential to explain growth in China (Song et al '11) and the Asian Tiger economies (Buera & Shin '13). 

To quantify the importance of initial conditions, we provide a unified model and estimation framework that allows to study dynamic economies in which growth is influenced both by initial conditions and aggregate changes over time. The model framework allows initial conditions to play a flexible role both through the accumulation of factors of production and through the reallocation of resources across plants in the economy. In this model setup, initial conditions are given by the entire distribution of producing plants, requiring to track the distribution of plants over time. To study realistic features of dynamic economies and to disentangle the role of initial conditions from other drivers of growth, we further incorporate changes in technology, changes in frictions over time and other changes in the aggregate economy (such as time-varying population growth) in a standard general equilibrium Hopenhayn model of plant dynamics with endogenous entry and exit. 

Estimating the model on our micro data along the observed transition path, we find that about 20% of the observed growth over the period 1975-2015 is explained by simply letting initial conditions in 1975 play out. The growth due to initial conditions plays out slowly over time as resources only slowly reallocate across plants (driven by sizable financial and labor market frictions). While selection dynamics of plants are relatively fast (90% of the long-run average plant productivity gains are reached after 10 years), reallocation processes take more than 20 years. Importantly, initial conditions do not become meaningfully less important over time. The reason is that while initial conditions push the economy towards a new stationary distribution, other changes in the economy continuously shift this stationary distribution. Initial conditions do not become less important over time if transition dynamics are slower than changes in primitives that are moving the stationary distribution. We find strong evidence for this in the Indonesian data, driven mostly by sizable changes in aggregate technology and the distribution and mass of potential entrants.

While my JMP focuses on the supply side of the dynamics of development, in my ongoing work on *Income Inequality and the Dynamics of Structural Change*, I look more closely at the demand side and demand heterogeneity: how demand changes over the course of development and how this affects industrialization and changes in the industrial structure of economies over time. For this, I draw on extensive Indian micro data, both at the household and worker level as well as the plant level. I start by motivating the importance of income effects and income inequality in driving structural change (the reallocation of resources across broad sectors of the economy). Product-level or sector-level demand, by definition, is a function of the entire income and preference distribution as well as prices and quality across all products. Drawing on representative household-level consumption data, I show that simply taking demand at the product and sector level across the entire income distribution in 1987, but now feeding in the income distribution 25 years later (and thereby fixing prices, preferences and quality), explains about 60-80% of structural change out of agriculture and more than 100% of the structural change into manufacturing. These numbers are surprisingly close to recent structural papers that have tried to disentangle income from supply-side effects without accounting for household heterogeneity (e.g. Comin et al '21, Alder et al '22). 

I show that observed demand heterogeneity over the entire income distribution is crucial not just to answer questions on the role of inequality in driving structural change and development, but also to disentangle mechanisms. In standard models of structural change, structural change is driven by a combination of endogenous income effects on the demand side and exogenous changes in technologies on the supply side. In this story, changes in technology induce economic growth that drives up income and feeds back into changes in demand, but demand changes do not affect technological change. To quantify the importance of dynamic demand effects on future technological change - a key mechanism in most models of endogenous growth such as learning-by-doing and purposeful investments in R&D - I link the previous exercise to changes in productivity at the plant-level. That is, I use changes in the income distribution over time to obtain heterogeneous demand shifters in the absence of any future changes in preferences, prices, productivity and quality. I then ask whether industries that - based on demand in 1987 - were expected to see differentially large increases in demand over time, also see differentially large increases in productivity. This exercise allows me to quantify the importance of dynamic productivity effects. At the moment, I am both finishing this quantification and building a structural model to account for Indian structural change since 1987. 

## The Political Economy of Development (or how the state and private sector interact over the course of development)

I believe that a major determinant of development is how political and economic institutions and actors intertwine. I study this question from two perspectives. On the one hand, I study how economic and political elites may collude for their own benefit, potentially undermining the workings of the economy (Paper on Political Connections). On the other hand, I study how the government interacts with the private sector over the course of development: for example, via the provision of public goods (Paper on Political Connections and the Decentralization Paper) and the evolution of state capacity over time (Work on State Capacity) as well as by affecting who works for the private and public sector over time (Working Paper on Government Worker selection). 

In my paper on Political Connections, I quantify the aggregate costs of political connections by building a model of heterogeneous firms where political connections distort the scale of production and firms endogenously spend resources on rent-seeking. Drawing on a large micro-empirical literature that gives direct evidence that political connections help obtain government favors such as direct input and output subsidies, monopoly rights, market power and tax evasion, I try to quantify the role of connections in distorting the observed firm-size distribution. The key empirical challenge is that in the data, large connected firms may be large because they are very productive, because they receive large subsidies or some combination of the two, with the extent of subsidies being directly correlated with underlying firm characteristics. For example, very productive firms may also be more productive at lobbying and other rent-seeking activities. I show how to separately identify subsidies and firm productivity by making assumptions on how connected firms are selected and show how the entire firm-size distribution of connected firms puts structure on what selection is plausible in the data. Backing out unobserved subsidies non-parametrically, I can then build a rich model of endogenous rent-seeking activities, which I use to understand the distribution of rent-seeking activities across firms and to study the aggregate costs of political connections in general equilibrium. For the case of Indonesia, I find that political connections annually cost between 1.0-4.7% of aggregate output. At most 45% of these output costs can be explained by misallocation of factors of production. The large remainder is explained by subsidizing connected firms instead of putting saved subsidies to more productive use. In comparison to the literature, besides the novel non-parametric estimation approach, there are at least two important insights: first, misallocation costs are not necessarily the most important costs of firm-level distortions as opportunity costs of public funds can be large, and second, a few firms (in the Indonesian data about 1% of firms who account for about 10% of output) can cause large aggregate costs. 

In other on-going research, I zoom in on the functioning of governments in developing countries. I propose a generally applicable identification strategy for the skill distribution of government workers that helps shed light on the selection process of government workers and their experience accumulation. This is part of a broader project of reconceptualizing state capacity through a production function lense. In such a framework, state capacity is fundamentally determined by the skills of workers who work for the state and how these workers are managed. I then explore a number of ways through which my approach can be used to quantitatively study new and interesting questions related to the study of state capacity. 

## Future work and open questions in Macro Development

In my future work, I aim to build on my previous research and extend it into a number of different directions. Specifically, I see 4 main areas of research that I deem extremely important for moving forward: (1) The drivers of growth, (2) integrating growth and political economy, (3) Behavioral Structural Macro Dev & long-run expectations, (4) developing structural models for better policy evaluation. I discuss each in turn. 

**The drivers of growth**: I think there are still huge returns to using rich micro data in combination with structural models to explain and disentangle the drivers of economic growth and development. For example, we have a large variety of theories on economic growth where growth is driven by learning-by-doing, R&D, human capital externalities and more general knowledge spillovers, technology diffusion, market power, undoing of misallocation, institutional change, etc. Being able to better distinguish between these drivers and quantifying their relative importance and exact mechanisms is key for policy. As I show in my JMP, there are tractable ways to identify dynamic mechanisms of development by estimating models on micro data along observed transition paths. In this paper, we identify the role of aggregate technology that maps directly to models of endogenous growth. A natural next step is to further endogenize aggregate technology and see how this can help to disentangle different theories of endogenous growth. One concrete example is the importance of distinguishing between Schumpeterian models of economic growth and growth due to aggregate technology changes as in the Hopenhayn-model tradition. These are fundamentally different ways to think about growth and both cannot be true at the same time - being able to distinguish them is a key open question that has not received enough attention in my eyes. Improvements on this side will also have important implications for the rest of the literature as it makes it easier to link a vast variety of frictions and market failures studied in the (Macro) Development literature to the dynamics of development. It also shifts the focus from long-run drivers of growth (at the steady state or balanced growth path) to drivers of actual growth in the data, making it arguably better suited for direct policy advice. 

**Integrating growth and political economy**: A second avenue of future research is to better link the study of economic growth and development to political economy issues. While there seems to be a consensus in the Development literature that the state and state capacity matters greatly for observed development, there is much less quantitative work on how exactly this link works and evolves over time. In my previous research and on-going work on conceptualizing state capacity, I try to contribute to this literature. I think that there are large returns to this research agenda, especially if it would be possible to integrate research from other disciplines, foremost Political Science. Being more specific on how institutions affect the behavior of individuals and firms over longer periods of time and how this aggregates up to economy-wide changes would create a valuable link between a structural literature in Economics that evaluates concrete policies and a mostly reduced-form literature in Economic History, Political Economy and Comparative Politics that studies state capacity and how institutions affect aggregate outcomes over long periods of time. 

**Behavioral Structural Macro Dev & long-run expectations**: Next, I see a big gap in the Macro Development literature on integrating insights from the Behavioral (structural) Economics literature. This is unfortunate because many behavioral mechanisms clearly have important implications for long-run development. For example, forms of myopia, hyperbolic discounting, time inconsistencies and self-control problems have important implications for savings and entrepreneurial choices. There are also important questions on how agents (individuals, firms, households, etc.) form long-run expectations, which are key for long-run development and have seen little empirical validation nor modeling in the Macro Development literature. 

**Developing structural models for better policy evaluation**: At last, I am interested in how structural modeling can be better used for robust policy evaluation and making good predictions. A big benefit of structural models is to be able to provide ex ante policy advice that does not require costly economy-wide experimentation. However, this hinges on the power of structural models to predict counterfactual changes in the economy. To date, I do not think that there is sufficient evidence that most structural models pass this test. This is in part because structural models (if at all) are mostly only tested in-sample and because counterfactual predictions are hard to evaluate ex post, because most counterfactual policies are never realized. I think there are many ways to move forward here: better out-of-sample model validation, more constrained estimation via methods widely used in other areas of science (e.g. cross-validation), more systematic ex post evaluation of structural models, a closer combination of reduced-form and structural approaches etc. All of these ideas have been applied in some form or another across research in Economics, but in my opinion there is still a long way to go in the areas of Macro Development and Growth. 
