---
title: "The Consequences of Political Connections - Quantifying the Effect of Firm-Size Distortions on Development in Indonesia"
author: "Jonas Gathen"
date: "`r format(Sys.Date(), format = '%b %d, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this paper I look at the role of political connections in the development process by building a model of a rich firm-size distribution where political connections distort the scale of production. Drawing on direct evidence that political connections help obtain government favors such as direct input and output subsidies, monopoly rights, market power and tax evasion, I try to quantify the role of connections in distorting the observed firm-size distribution. The idea is that politically connected firms are larger than they would be without government help and by building a structural model of this process, I can shed light on how much the government is helping connected firms by observing the actual size of differentially connected firms. In the model, I allow rich correlation between political connections and other determinants of firm-size such as underlying productivity. 

What are the costs of these connections? One can think of this as money spent on connected firms that could have otherwise been returned to households via lower taxes or direct transfers. In a development context where the government provides crucial education and infrastructure, the more natural counterfactual is what alternative investments the government could have made and what implications these investments could have had on long-run growth and development. To answer this question, I directly model productive public goods such as infrastructure, education and other institutions, which enter firms' production functions. Political connections thus have aggregate effects through their detrimental effect on institutions. I then consider the aggregate consequences along a realistic transition path.

To assess the aggregate consequences of political connections, I fit the model to the case of Indonesia, using detailed firm-level panel data including firm-level information on political connections. I identify the role of government institutions using the natural experiment of Indonesia's recent decentralization process that plausibly exogenously reallocated resources across local governments. Identification of the other parameters follows a Simulated Method of Moments approach where I match key empirical moments of the Indonesian economy and the underlying firm-level data. This approach allows rich endogeneity regarding the choice and investments in political connections. 