---
title: Multiple Causes
author: 'Jonas Gathen'
date: '2018-08-15'
slug: multiple-causes
categories: []
tags: []
description: ''
---

The credibility revolution of the past decades in Economics and the social sciences in general has had a tremendous impact. Everyone talks about identification strategies and causal effects, about treatments and various treatment effects. I laud this general development, though in my opinion it has also led many research agendas to be guided by fairly reductionist accounts of causality. We are looking for THE causal effect from education to income, from THE causal effect from institutions to economic growth, from THE causal effect from x to y. 

- Literature on causality from a philosophy of science perspective
- Even if we get to isolate a causal effect, it is only A causal effect, not THE causal effect. Excluding reverse causality through a good identification strategy doesn't mean that reverse causality doesn't play a role, it just means that we can estimate the causal effect for the direction we are interested in, without having it confounded by the reverse effect. 

- Multiple causes: ML literature (recent 2018 paper);
- Multiple causes as selection issue. If we think about causal mechanisms and effects being omnipresent - everything effects everything - and we assume that each of the effects by itself (though there are important interactions of causal mechanisms) is not very important, we only see large aggregate effects if we see a large combination of causal mechanisms. This is consequential for social research, because our research is usually guided by aggregate effects society deems important. Viewed from this angle, we can treat the aggregate effects that guide much of social science research as a selection problem; we only observe the effects that don't cancel out or at least we don't pay much attention to the different causal mechanisms that push into different directions and whose aggregate effects are thus not easily visible.
There is an implicit and often also explicit assumption that if we observe some important aggregate effects (e.g. consumer bankruptcy cases increase, measured aggregate productivity is growing much slower today, authoritarianism is globally on the rise, etc.), this must be caused by a limited number of important causal mechanisms otherwise we would not see the effect. This is obviously not true; the reason why we observe the effect is because some causal mechanisms do not cancel out; it could be that this is driven by a few causal mechanisms, but it could also be that this is driven by many. 

One can have many different models of causal effects; correlated effects, contextual effects, effects that switch directions, etc. 




